server:
  port: 18088
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    port: 6379
    host: 192.168.236.128
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug
ThreadPool:
  corePoolSize: 100
  maxmumPoolSize: 500
  keepAliveTime: 60
  blockingQueue: 5000